version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    build:
      context: ./environment/site
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "4000:80"
    networks:
      - webnet
  database:
    build:
      context: ./environment/database
      dockerfile: Dockerfile
    networks:
      - webnet
    env_file:
      - environment/database/secret.env
    ports:
      - "27017:27017"
networks:
  webnet: